class_name COMPONENT_TYPE

enum{
	ACTION_MENU_COMPONENT,
	BLOCK_MENU_COMPONENT,
	COLLIDER_COMPONENT,
	FIELD_COMPONENT,
	FOLLOW_STAY_MENU_COMPONENT,
	INPUT_COMPONENT,
	SELECT_COMPONENT,
	ROLL_DISPLAY_COMPONENT,
	PLAYER_UI_COMPONENT,
}

