class_name PuzzleGeneratorTestData
extends Object


static func no_players_ball_on_field() -> String:
	return '{"ball_position":[1,1],"creator_name":"test","game_version":"0.01","is_ball_on_field":true,"opponent_team":[],"opponent_team_type":0,"player_team":[],"player_team_type":0,"puzzle_description":"test","puzzle_name":"test","puzzle_type":0}'

static func one_player_ball_on_field() -> String:
	return '{"ball_position":[1,1],"creator_name":"test","game_version":"0.01","is_ball_on_field":true,"opponent_team":[],"opponent_team_type":0,"player_team":[{"grid_coordinate":[7,6],"has_ball":false,"is_on_sideboard":false,"skills":{"0":true,"1":false,"2":false,"3":false,"4":false},"stats":{"AG":2,"AV":8,"MA":9,"PA":2,"STR":2},"type":"gutter_runner"}],"player_team_type":0,"puzzle_description":"test","puzzle_name":"test","puzzle_type":0}'

static func one_player_ball_on_player() -> String:
	return '{"ball_position":[7,6],"creator_name":"test","game_version":"0.01","is_ball_on_field":false,"opponent_team":[],"opponent_team_type":0,"player_team":[{"grid_coordinate":[7,6],"has_ball":true,"is_on_sideboard":false,"skills":{"0":true,"1":false,"2":false,"3":false,"4":false},"stats":{"AG":2,"AV":8,"MA":9,"PA":2,"STR":2},"type":"gutter_runner"}],"player_team_type":0,"puzzle_description":"test","puzzle_name":"test","puzzle_type":0}'

static func one_player_one_opponent_ball_on_field() -> String:
	return '{"ball_position":[1,1],"creator_name":"test","game_version":"0.01","is_ball_on_field":true,"opponent_team":[{"grid_coordinate":[7,17],"has_ball":false,"is_on_sideboard":false,"skills":{"0":true,"1":false,"2":false,"3":false,"4":false},"stats":{"AG":2,"AV":8,"MA":9,"PA":2,"STR":2},"type":"gutter_runner"}],"opponent_team_type":0,"player_team":[{"grid_coordinate":[7,6],"has_ball":false,"is_on_sideboard":false,"skills":{"0":true,"1":false,"2":false,"3":false,"4":false},"stats":{"AG":2,"AV":8,"MA":9,"PA":2,"STR":2},"type":"gutter_runner"}],"player_team_type":0,"puzzle_description":"test","puzzle_name":"test","puzzle_type":0}'

static func one_player_one_opponent_ball_on_player() ->String:
	return '{"ball_position":[7,5],"creator_name":"test","game_version":"0.01","is_ball_on_field":false,"opponent_team":[{"grid_coordinate":[7,15],"has_ball":false,"is_on_sideboard":false,"skills":{"0":true,"1":false,"2":false,"3":false,"4":false},"stats":{"AG":2,"AV":8,"MA":9,"PA":2,"STR":2},"type":"gutter_runner"}],"opponent_team_type":0,"player_team":[{"grid_coordinate":[7,5],"has_ball":true,"is_on_sideboard":false,"skills":{"0":true,"1":false,"2":false,"3":false,"4":false},"stats":{"AG":2,"AV":8,"MA":9,"PA":2,"STR":2},"type":"gutter_runner"}],"player_team_type":0,"puzzle_description":"test","puzzle_name":"test","puzzle_type":0}'

static func one_player_one_opponent_ball_on_opponent() -> String:
	return '{"ball_position":[7,17],"creator_name":"test","game_version":"0.01","is_ball_on_field":false,"opponent_team":[{"grid_coordinate":[7,17],"has_ball":true,"is_on_sideboard":false,"skills":{"0":true,"1":false,"2":false,"3":false,"4":false},"stats":{"AG":2,"AV":8,"MA":9,"PA":2,"STR":2},"type":"gutter_runner"}],"opponent_team_type":0,"player_team":[{"grid_coordinate":[7,6],"has_ball":false,"is_on_sideboard":false,"skills":{"0":true,"1":false,"2":false,"3":false,"4":false},"stats":{"AG":2,"AV":8,"MA":9,"PA":2,"STR":2},"type":"gutter_runner"}],"player_team_type":0,"puzzle_description":"test","puzzle_name":"test","puzzle_type":0}'

static func multi_player_ball_on_field() ->String:
	return '{"ball_position":[1,1],"creator_name":"test","game_version":"0.01","is_ball_on_field":true,"opponent_team":[{"grid_coordinate":[6,16],"has_ball":false,"is_on_sideboard":false,"skills":{"0":true,"1":false,"2":false,"3":false,"4":false},"stats":{"AG":2,"AV":8,"MA":9,"PA":2,"STR":2},"type":"gutter_runner"},{"grid_coordinate":[9,16],"has_ball":false,"is_on_sideboard":false,"skills":{"0":true,"1":false,"2":false,"3":false,"4":false},"stats":{"AG":2,"AV":8,"MA":9,"PA":2,"STR":2},"type":"gutter_runner"},{"grid_coordinate":[2,16],"has_ball":false,"is_on_sideboard":false,"skills":{"0":false,"1":false,"2":false,"3":false,"4":false},"stats":{"AG":3,"AV":8,"MA":7,"PA":3,"STR":3},"type":"line_rat"},{"grid_coordinate":[6,20],"has_ball":false,"is_on_sideboard":false,"skills":{"0":true,"1":false,"2":false,"3":false,"4":false},"stats":{"AG":2,"AV":8,"MA":9,"PA":2,"STR":2},"type":"gutter_runner"},{"grid_coordinate":[10,20],"has_ball":false,"is_on_sideboard":false,"skills":{"0":false,"1":false,"2":false,"3":false,"4":false},"stats":{"AG":3,"AV":8,"MA":7,"PA":3,"STR":3},"type":"line_rat"},{"grid_coordinate":[2,20],"has_ball":false,"is_on_sideboard":false,"skills":{"0":true,"1":false,"2":false,"3":false,"4":false},"stats":{"AG":2,"AV":8,"MA":9,"PA":2,"STR":2},"type":"gutter_runner"}],"opponent_team_type":0,"player_team":[{"grid_coordinate":[5,5],"has_ball":false,"is_on_sideboard":false,"skills":{"0":true,"1":false,"2":false,"3":false,"4":false},"stats":{"AG":2,"AV":8,"MA":9,"PA":2,"STR":2},"type":"gutter_runner"},{"grid_coordinate":[8,7],"has_ball":false,"is_on_sideboard":false,"skills":{"0":false,"1":false,"2":false,"3":false,"4":false},"stats":{"AG":3,"AV":8,"MA":7,"PA":3,"STR":3},"type":"line_rat"},{"grid_coordinate":[3,9],"has_ball":false,"is_on_sideboard":false,"skills":{"0":true,"1":false,"2":false,"3":false,"4":false},"stats":{"AG":2,"AV":8,"MA":9,"PA":2,"STR":2},"type":"gutter_runner"},{"grid_coordinate":[11,10],"has_ball":false,"is_on_sideboard":false,"skills":{"0":false,"1":false,"2":false,"3":false,"4":false},"stats":{"AG":3,"AV":8,"MA":7,"PA":3,"STR":3},"type":"line_rat"},{"grid_coordinate":[9,3],"has_ball":false,"is_on_sideboard":false,"skills":{"0":true,"1":false,"2":false,"3":false,"4":false},"stats":{"AG":2,"AV":8,"MA":9,"PA":2,"STR":2},"type":"gutter_runner"},{"grid_coordinate":[2,5],"has_ball":false,"is_on_sideboard":false,"skills":{"0":false,"1":false,"2":false,"3":false,"4":false},"stats":{"AG":3,"AV":8,"MA":7,"PA":3,"STR":3},"type":"line_rat"}],"player_team_type":0,"puzzle_description":"test","puzzle_name":"test","puzzle_type":0}'

static func multi_player_ball_on_player() ->String:
	return '{"ball_position":[3,9],"creator_name":"test","game_version":"0.01","is_ball_on_field":false,"opponent_team":[{"grid_coordinate":[4,15],"has_ball":false,"is_on_sideboard":false,"skills":{"0":true,"1":false,"2":false,"3":false,"4":false},"stats":{"AG":2,"AV":8,"MA":9,"PA":2,"STR":2},"type":"gutter_runner"},{"grid_coordinate":[9,15],"has_ball":false,"is_on_sideboard":false,"skills":{"0":true,"1":false,"2":false,"3":false,"4":false},"stats":{"AG":2,"AV":8,"MA":9,"PA":2,"STR":2},"type":"gutter_runner"},{"grid_coordinate":[7,18],"has_ball":false,"is_on_sideboard":false,"skills":{"0":true,"1":false,"2":false,"3":false,"4":false},"stats":{"AG":2,"AV":8,"MA":9,"PA":2,"STR":2},"type":"gutter_runner"},{"grid_coordinate":[11,18],"has_ball":false,"is_on_sideboard":false,"skills":{"0":true,"1":false,"2":false,"3":false,"4":false},"stats":{"AG":2,"AV":8,"MA":9,"PA":2,"STR":2},"type":"gutter_runner"},{"grid_coordinate":[2,19],"has_ball":false,"is_on_sideboard":false,"skills":{"0":false,"1":false,"2":false,"3":false,"4":false},"stats":{"AG":3,"AV":8,"MA":7,"PA":3,"STR":3},"type":"line_rat"},{"grid_coordinate":[9,21],"has_ball":false,"is_on_sideboard":false,"skills":{"0":true,"1":false,"2":false,"3":false,"4":false},"stats":{"AG":2,"AV":8,"MA":9,"PA":2,"STR":2},"type":"gutter_runner"}],"opponent_team_type":0,"player_team":[{"grid_coordinate":[5,5],"has_ball":false,"is_on_sideboard":false,"skills":{"0":true,"1":false,"2":false,"3":false,"4":false},"stats":{"AG":2,"AV":8,"MA":9,"PA":2,"STR":2},"type":"gutter_runner"},{"grid_coordinate":[9,8],"has_ball":false,"is_on_sideboard":false,"skills":{"0":false,"1":false,"2":false,"3":false,"4":false},"stats":{"AG":3,"AV":8,"MA":7,"PA":3,"STR":3},"type":"line_rat"},{"grid_coordinate":[3,9],"has_ball":true,"is_on_sideboard":false,"skills":{"0":true,"1":false,"2":false,"3":false,"4":false},"stats":{"AG":2,"AV":8,"MA":9,"PA":2,"STR":2},"type":"gutter_runner"},{"grid_coordinate":[10,4],"has_ball":false,"is_on_sideboard":false,"skills":{"0":false,"1":false,"2":false,"3":false,"4":false},"stats":{"AG":3,"AV":8,"MA":7,"PA":3,"STR":3},"type":"line_rat"},{"grid_coordinate":[9,11],"has_ball":false,"is_on_sideboard":false,"skills":{"0":true,"1":false,"2":false,"3":false,"4":false},"stats":{"AG":2,"AV":8,"MA":9,"PA":2,"STR":2},"type":"gutter_runner"}],"player_team_type":0,"puzzle_description":"test","puzzle_name":"test","puzzle_type":0}'


